### ISSUE TITLE
[manila] manila-share-sync share instances should respect replicas

### ISSUE THREAD

**Issue by Carthaca** [sapcc/openstack-nannies#52]
https://github.com/sapcc/openstack-nannies/blob/cc6033dd6e94619f2df1c8d481675d98755540e6/scripts/manila-share-sync.py#L473 joins share instances on share_id and implicitly assumes this is a 1-1 relation, but a share can have multiple share instances, e.g. in a replication setup one instance exists with replica_state active and one or more instances may exist with replica_state not active [in_sync, out_of_sync ..] which could lead to surprises on the returned share_instance_id

**Comment by kpawar-sap** [comment]
Will be fixed by https://github.com/sapcc/openstack-nannies/pull/53

**Comment by chuan137** [comment]
the join function will select all records by matching the share_id, why it implicitly assumes 1-1 relation? I have not done any manual test yet. But on the first look, I feel it is ok

**Comment by chuan137** [comment]
```
select share_instances.id from shares join share_instances on shares.id = share_instances.share_id where shares.id = "cb626a38-6e28-46f0-8805-9f7e2d394d6b";
+--------------------------------------+
| id                                   |
+--------------------------------------+
| 27228a19-0524-4317-8692-bb89233ea1d6 |
| 27da2d70-1813-4503-88cf-51a1bf0ea23c |
+--------------------------------------+
```
I did a quick test with join, the statement select all replicas from the same share. @Carthaca have you observed any issue with selecting replicas in nanny?

**Comment by Carthaca** [comment]
My bad, I must have misread the method working on the result - sorry for the confusion
